import { CommandTable } from './command-table.ts';
import type {
  CommandDefinition,
  CommandFlag,
  CommandHandler,
} from './command-table.ts';
import * as connection from './commands/connection.ts';
import * as client from './commands/client.ts';
import * as generic from './commands/generic.ts';
import * as ttl from './commands/ttl.ts';
import * as scan from './commands/scan.ts';
import * as sort from './commands/sort.ts';
import * as string from './commands/string.ts';
import * as incr from './commands/incr.ts';
import * as hash from './commands/hash.ts';
import * as hashTtl from './commands/hash-ttl.ts';
import * as list from './commands/list.ts';
import * as set from './commands/set.ts';
import * as database from './commands/database.ts';
import * as cmd from './commands/command.ts';
import * as transaction from './commands/transaction.ts';
import * as bitmap from './commands/bitmap.ts';
import * as pubsub from './commands/pubsub.ts';
import * as sortedSet from './commands/sorted-set.ts';
import * as streamCmd from './commands/stream.ts';
import * as mem from './commands/memory.ts';
import * as infoCmd from './commands/info.ts';
import type { CommandContext } from './types.ts';

function getTable(ctx: CommandContext): CommandTable {
  if (!ctx.commandTable) {
    throw new Error('commandTable not set on context');
  }
  return ctx.commandTable;
}

interface CommandSpec {
  name: string;
  handler: CommandHandler;
  arity: number;
  flags: CommandFlag[];
  firstKey: number;
  lastKey: number;
  keyStep: number;
  categories: string[];
  subcommands?: CommandSpec[];
}

function toDefinition(spec: CommandSpec): CommandDefinition {
  const def: CommandDefinition = {
    name: spec.name,
    handler: spec.handler,
    arity: spec.arity,
    flags: new Set(spec.flags),
    firstKey: spec.firstKey,
    lastKey: spec.lastKey,
    keyStep: spec.keyStep,
    categories: new Set(spec.categories),
  };
  if (spec.subcommands) {
    def.subcommands = new Map();
    for (const sub of spec.subcommands) {
      def.subcommands.set(sub.name.toLowerCase(), toDefinition(sub));
    }
  }
  return def;
}

/**
 * All currently implemented commands.
 * Arity follows Redis convention: includes command name.
 * Positive = exact, negative = minimum.
 */
const commandSpecs: CommandSpec[] = [
  // --- Connection commands ---
  {
    name: 'ping',
    handler: (_ctx, args) => connection.ping(args),
    arity: -1,
    flags: ['fast', 'stale', 'loading'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'echo',
    handler: (_ctx, args) => connection.echo(args),
    arity: 2,
    flags: ['fast', 'stale', 'loading'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'quit',
    handler: () => connection.quit(),
    arity: -1,
    flags: ['fast', 'noscript', 'stale', 'loading', 'noauth'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'reset',
    handler: () => connection.reset(),
    arity: 1,
    flags: ['fast', 'noscript', 'loading', 'stale', 'noauth'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'hello',
    handler: (ctx, args) => connection.hello(ctx, args),
    arity: -1,
    flags: ['fast', 'loading', 'stale', 'noauth'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'auth',
    handler: (ctx, args) => connection.auth(ctx, args),
    arity: -2,
    flags: ['fast', 'loading', 'stale', 'noauth', 'noscript'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },

  // --- Database commands ---
  {
    name: 'select',
    handler: (ctx, args) => database.select(ctx, args),
    arity: 2,
    flags: ['fast', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@connection'],
  },
  {
    name: 'dbsize',
    handler: (ctx) => database.dbsize(ctx.db),
    arity: 1,
    flags: ['readonly', 'fast', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@read', '@fast'],
  },
  {
    name: 'flushdb',
    handler: (ctx, args) => database.flushdb(ctx, args),
    arity: -1,
    flags: ['write', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'flushall',
    handler: (ctx, args) => database.flushall(ctx, args),
    arity: -1,
    flags: ['write', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'swapdb',
    handler: (ctx, args) => database.swapdb(ctx.engine, args),
    arity: 3,
    flags: ['write', 'fast'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@write', '@fast'],
  },

  // --- Client commands ---
  {
    name: 'client',
    handler: (ctx, args) => client.client(ctx, args),
    arity: -2,
    flags: ['admin', 'noscript', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@admin', '@slow', '@connection'],
    subcommands: [
      {
        name: 'id',
        handler: (ctx) => client.clientId(ctx.client),
        arity: 2,
        flags: ['fast', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'getname',
        handler: (ctx) => client.clientGetname(ctx.client),
        arity: 2,
        flags: ['fast', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'setname',
        handler: (ctx, args) => client.clientSetname(ctx.client, args.slice(1)),
        arity: 3,
        flags: ['fast', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'list',
        handler: (ctx, args) =>
          client.clientList(
            ctx.clientStore,
            ctx.client,
            ctx.engine.clock,
            args.slice(1)
          ),
        arity: -2,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'info',
        handler: (ctx) => client.clientInfo(ctx.client, ctx.engine.clock),
        arity: 2,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'kill',
        handler: (ctx, args) =>
          client.clientKill(ctx.clientStore, ctx.client, args.slice(1)),
        arity: -3,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'pause',
        handler: () => client.clientPause(),
        arity: -3,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'unpause',
        handler: () => client.clientUnpause(),
        arity: 2,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'reply',
        handler: (ctx, args) => client.clientReply(args.slice(1)),
        arity: 3,
        flags: ['fast', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'no-evict',
        handler: (ctx, args) => client.clientNoEvict(ctx.client, args.slice(1)),
        arity: 3,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'no-touch',
        handler: (ctx, args) => client.clientNoTouch(ctx.client, args.slice(1)),
        arity: 3,
        flags: ['admin', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@admin', '@slow', '@connection'],
      },
      {
        name: 'tracking',
        handler: (ctx, args) =>
          client.clientTracking(ctx.client, ctx.clientStore, args.slice(1)),
        arity: -3,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'caching',
        handler: (ctx, args) => client.clientCaching(ctx.client, args.slice(1)),
        arity: 3,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'trackinginfo',
        handler: (ctx) => client.clientTrackinginfo(ctx.client),
        arity: 2,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'getredir',
        handler: (ctx) => client.clientGetredir(ctx.client),
        arity: 2,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'help',
        handler: () => client.clientHelp(),
        arity: 2,
        flags: ['loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
    ],
  },

  // --- Transaction commands ---
  {
    name: 'multi',
    handler: () => transaction.multi(),
    arity: 1,
    flags: ['noscript', 'loading', 'stale', 'fast'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@transaction'],
  },
  {
    name: 'exec',
    handler: () => transaction.exec(),
    arity: 1,
    flags: ['noscript', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@slow', '@transaction'],
  },
  {
    name: 'discard',
    handler: () => transaction.discard(),
    arity: 1,
    flags: ['noscript', 'loading', 'stale', 'fast'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@fast', '@transaction'],
  },

  // --- Generic (keyspace) commands ---
  {
    name: 'del',
    handler: (ctx, args) => generic.del(ctx.db, args),
    arity: -2,
    flags: ['write'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'unlink',
    handler: (ctx, args) => generic.unlink(ctx.db, args),
    arity: -2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'exists',
    handler: (ctx, args) => generic.exists(ctx.db, args),
    arity: -2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'type',
    handler: (ctx, args) => generic.type(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'rename',
    handler: (ctx, args) => generic.rename(ctx.db, args),
    arity: 3,
    flags: ['write'],
    firstKey: 1,
    lastKey: 2,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'renamenx',
    handler: (ctx, args) => generic.renamenx(ctx.db, args),
    arity: 3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 2,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'persist',
    handler: (ctx, args) => generic.persist(ctx.db, args),
    arity: 2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'randomkey',
    handler: (ctx) => generic.randomkey(ctx.db),
    arity: 1,
    flags: ['readonly'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'touch',
    handler: (ctx, args) => generic.touch(ctx.db, args),
    arity: -2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'copy',
    handler: (ctx, args) => generic.copy(ctx.engine, ctx.db, args),
    arity: -3,
    flags: ['write'],
    firstKey: 1,
    lastKey: 2,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'object',
    handler: (ctx, args) => generic.object(ctx.db, ctx.engine.clock, args),
    arity: -2,
    flags: ['readonly'],
    firstKey: 2,
    lastKey: 2,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
    subcommands: [
      {
        name: 'encoding',
        handler: (ctx, args) => generic.objectEncoding(ctx.db, args),
        arity: 3,
        flags: ['readonly'],
        firstKey: 2,
        lastKey: 2,
        keyStep: 1,
        categories: ['@keyspace', '@read'],
      },
      {
        name: 'refcount',
        handler: (ctx, args) => generic.objectRefcount(ctx.db, args),
        arity: 3,
        flags: ['readonly'],
        firstKey: 2,
        lastKey: 2,
        keyStep: 1,
        categories: ['@keyspace', '@read'],
      },
      {
        name: 'idletime',
        handler: (ctx, args) =>
          generic.objectIdletimeWithClock(ctx.db, ctx.engine.clock, args),
        arity: 3,
        flags: ['readonly'],
        firstKey: 2,
        lastKey: 2,
        keyStep: 1,
        categories: ['@keyspace', '@read'],
      },
      {
        name: 'freq',
        handler: (ctx, args) => generic.objectFreq(ctx.db, args),
        arity: 3,
        flags: ['readonly'],
        firstKey: 2,
        lastKey: 2,
        keyStep: 1,
        categories: ['@keyspace', '@read'],
      },
      {
        name: 'help',
        handler: () => generic.objectHelp(),
        arity: 2,
        flags: ['readonly'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@keyspace', '@read'],
      },
    ],
  },
  {
    name: 'memory',
    handler: (ctx, args) => mem.memory(ctx.db, ctx.engine, args),
    arity: -2,
    flags: ['readonly'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@slow'],
    subcommands: [
      {
        name: 'usage',
        handler: (ctx, args) => mem.memoryUsage(ctx.db, args),
        arity: -3,
        flags: ['readonly'],
        firstKey: 2,
        lastKey: 2,
        keyStep: 1,
        categories: ['@slow'],
      },
      {
        name: 'doctor',
        handler: () => mem.memoryDoctor(),
        arity: 2,
        flags: ['readonly'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow'],
      },
      {
        name: 'malloc-stats',
        handler: () => mem.memoryMallocStats(),
        arity: 2,
        flags: ['readonly'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow'],
      },
      {
        name: 'purge',
        handler: () => mem.memoryPurge(),
        arity: 2,
        flags: [],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow'],
      },
      {
        name: 'stats',
        handler: (ctx) => mem.memoryStats(ctx.engine),
        arity: 2,
        flags: ['readonly'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow'],
      },
      {
        name: 'help',
        handler: () => mem.memoryHelp(),
        arity: 2,
        flags: ['readonly'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow'],
      },
    ],
  },
  {
    name: 'wait',
    handler: () => generic.wait(),
    arity: 3,
    flags: ['readonly'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@generic'],
  },
  {
    name: 'dump',
    handler: () => generic.dump(),
    arity: 2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'restore',
    handler: () => generic.restore(),
    arity: -4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },

  // --- TTL commands ---
  {
    name: 'expire',
    handler: (ctx, args) => ttl.expire(ctx.db, ctx.engine.clock, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'pexpire',
    handler: (ctx, args) => ttl.pexpire(ctx.db, ctx.engine.clock, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'expireat',
    handler: (ctx, args) => ttl.expireat(ctx.db, ctx.engine.clock, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'pexpireat',
    handler: (ctx, args) => ttl.pexpireat(ctx.db, ctx.engine.clock, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@write'],
  },
  {
    name: 'ttl',
    handler: (ctx, args) => ttl.ttl(ctx.db, ctx.engine.clock, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'pttl',
    handler: (ctx, args) => ttl.pttl(ctx.db, ctx.engine.clock, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'expiretime',
    handler: (ctx, args) => ttl.expiretime(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'pexpiretime',
    handler: (ctx, args) => ttl.pexpiretime(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@keyspace', '@read'],
  },

  // --- Scan commands ---
  {
    name: 'keys',
    handler: (ctx, args) => scan.keys(ctx.db, args),
    arity: 2,
    flags: ['readonly'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@read'],
  },
  {
    name: 'scan',
    handler: (ctx, args) => scan.scan(ctx.db, args),
    arity: -2,
    flags: ['readonly'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@keyspace', '@read'],
  },

  // --- Sort commands ---
  {
    name: 'sort',
    handler: (ctx, args) => sort.sort(ctx.db, args),
    arity: -2,
    flags: ['write', 'denyoom', 'movablekeys'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@set', '@sortedset', '@list'],
  },
  {
    name: 'sort_ro',
    handler: (ctx, args) => sort.sortRo(ctx.db, args),
    arity: -2,
    flags: ['readonly', 'movablekeys'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set', '@sortedset', '@list'],
  },

  // --- String commands ---
  {
    name: 'get',
    handler: (ctx, args) => string.get(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@string', '@fast'],
  },
  {
    name: 'set',
    handler: (ctx, args) => string.set(ctx.db, ctx.engine.clock, args),
    arity: -3,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string'],
  },
  {
    name: 'mget',
    handler: (ctx, args) => string.mget(ctx.db, args),
    arity: -2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 1,
    categories: ['@read', '@string', '@fast'],
  },
  {
    name: 'mset',
    handler: (ctx, args) => string.mset(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 2,
    categories: ['@write', '@string'],
  },
  {
    name: 'msetnx',
    handler: (ctx, args) => string.msetnx(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: -1,
    keyStep: 2,
    categories: ['@write', '@string'],
  },
  {
    name: 'append',
    handler: (ctx, args) => string.append(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'strlen',
    handler: (ctx, args) => string.strlen(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@string', '@fast'],
  },
  {
    name: 'setrange',
    handler: (ctx, args) => string.setrange(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string'],
  },
  {
    name: 'getrange',
    handler: (ctx, args) => string.getrange(ctx.db, args),
    arity: 4,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@string'],
  },
  {
    name: 'substr',
    handler: (ctx, args) => string.getrange(ctx.db, args),
    arity: 4,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@string'],
  },
  {
    name: 'getex',
    handler: (ctx, args) => string.getex(ctx.db, ctx.engine.clock, args),
    arity: -2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'getdel',
    handler: (ctx, args) => string.getdel(ctx.db, args),
    arity: 2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'getset',
    handler: (ctx, args) => string.getset(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'setnx',
    handler: (ctx, args) => string.setnx(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'setex',
    handler: (ctx, args) => string.setex(ctx.db, ctx.engine.clock, args),
    arity: 4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string'],
  },
  {
    name: 'psetex',
    handler: (ctx, args) => string.psetex(ctx.db, ctx.engine.clock, args),
    arity: 4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string'],
  },
  {
    name: 'lcs',
    handler: (ctx, args) => string.lcs(ctx.db, args),
    arity: -3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 2,
    keyStep: 1,
    categories: ['@read', '@string'],
  },

  // --- INCR/DECR family ---
  {
    name: 'incr',
    handler: (ctx, args) => incr.incr(ctx.db, args),
    arity: 2,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'decr',
    handler: (ctx, args) => incr.decr(ctx.db, args),
    arity: 2,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'incrby',
    handler: (ctx, args) => incr.incrby(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'decrby',
    handler: (ctx, args) => incr.decrby(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },
  {
    name: 'incrbyfloat',
    handler: (ctx, args) => incr.incrbyfloat(ctx.db, args),
    arity: 3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@string', '@fast'],
  },

  // --- Bitmap commands ---
  {
    name: 'setbit',
    handler: (ctx, args) => bitmap.setbit(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@bitmap'],
  },
  {
    name: 'getbit',
    handler: (ctx, args) => bitmap.getbit(ctx.db, args),
    arity: 3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@bitmap', '@fast'],
  },
  {
    name: 'bitcount',
    handler: (ctx, args) => bitmap.bitcount(ctx.db, args),
    arity: -2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@bitmap'],
  },
  {
    name: 'bitpos',
    handler: (ctx, args) => bitmap.bitpos(ctx.db, args),
    arity: -3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@bitmap'],
  },
  {
    name: 'bitop',
    handler: (ctx, args) => bitmap.bitop(ctx.db, args),
    arity: -4,
    flags: ['write', 'denyoom'],
    firstKey: 2,
    lastKey: -1,
    keyStep: 1,
    categories: ['@write', '@bitmap'],
  },
  {
    name: 'bitfield',
    handler: (ctx, args) => bitmap.bitfield(ctx.db, args),
    arity: -2,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@bitmap'],
  },
  {
    name: 'bitfield_ro',
    handler: (ctx, args) => bitmap.bitfieldRo(ctx.db, args),
    arity: -2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@bitmap', '@fast'],
  },

  // --- Hash commands ---
  {
    name: 'hset',
    handler: (ctx, args) => hash.hset(ctx.db, args),
    arity: -4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hget',
    handler: (ctx, args) => hash.hget(ctx.db, args),
    arity: 3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hmset',
    handler: (ctx, args) => hash.hmset(ctx.db, args),
    arity: -4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hmget',
    handler: (ctx, args) => hash.hmget(ctx.db, args),
    arity: -3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hgetall',
    handler: (ctx, args) => hash.hgetall(ctx.db, args),
    arity: 2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash'],
  },
  {
    name: 'hdel',
    handler: (ctx, args) => hash.hdel(ctx.db, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hexists',
    handler: (ctx, args) => hash.hexists(ctx.db, args),
    arity: 3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hlen',
    handler: (ctx, args) => hash.hlen(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hkeys',
    handler: (ctx, args) => hash.hkeys(ctx.db, args),
    arity: 2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash'],
  },
  {
    name: 'hvals',
    handler: (ctx, args) => hash.hvals(ctx.db, args),
    arity: 2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash'],
  },
  {
    name: 'hsetnx',
    handler: (ctx, args) => hash.hsetnx(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hincrby',
    handler: (ctx, args) => hash.hincrby(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hincrbyfloat',
    handler: (ctx, args) => hash.hincrbyfloat(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hrandfield',
    handler: (ctx, args) => hash.hrandfield(ctx.db, args, ctx.engine.rng),
    arity: -2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash'],
  },
  {
    name: 'hscan',
    handler: (ctx, args) => hash.hscan(ctx.db, args),
    arity: -3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash'],
  },

  // --- Hash field TTL commands (Redis 7.4+) ---
  {
    name: 'hexpire',
    handler: (ctx, args) => hashTtl.hexpire(ctx.db, ctx.engine.clock, args),
    arity: -6,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hpexpire',
    handler: (ctx, args) => hashTtl.hpexpire(ctx.db, ctx.engine.clock, args),
    arity: -6,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hexpireat',
    handler: (ctx, args) => hashTtl.hexpireat(ctx.db, ctx.engine.clock, args),
    arity: -6,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hpexpireat',
    handler: (ctx, args) => hashTtl.hpexpireat(ctx.db, ctx.engine.clock, args),
    arity: -6,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'httl',
    handler: (ctx, args) => hashTtl.httl(ctx.db, ctx.engine.clock, args),
    arity: -5,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hpttl',
    handler: (ctx, args) => hashTtl.hpttl(ctx.db, ctx.engine.clock, args),
    arity: -5,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hpersist',
    handler: (ctx, args) => hashTtl.hpersist(ctx.db, ctx.engine.clock, args),
    arity: -5,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@hash', '@fast'],
  },
  {
    name: 'hexpiretime',
    handler: (ctx, args) => hashTtl.hexpiretime(ctx.db, ctx.engine.clock, args),
    arity: -5,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },
  {
    name: 'hpexpiretime',
    handler: (ctx, args) =>
      hashTtl.hpexpiretime(ctx.db, ctx.engine.clock, args),
    arity: -5,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@hash', '@fast'],
  },

  // --- List commands ---
  {
    name: 'lpush',
    handler: (ctx, args) => list.lpush(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'rpush',
    handler: (ctx, args) => list.rpush(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'lpushx',
    handler: (ctx, args) => list.lpushx(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'rpushx',
    handler: (ctx, args) => list.rpushx(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'lpop',
    handler: (ctx, args) => list.lpop(ctx.db, args),
    arity: -2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'rpop',
    handler: (ctx, args) => list.rpop(ctx.db, args),
    arity: -2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@fast'],
  },
  {
    name: 'llen',
    handler: (ctx, args) => list.llen(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@list', '@fast'],
  },
  {
    name: 'lrange',
    handler: (ctx, args) => list.lrange(ctx.db, args),
    arity: 4,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@list', '@slow'],
  },
  {
    name: 'lindex',
    handler: (ctx, args) => list.lindex(ctx.db, args),
    arity: 3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@list', '@slow'],
  },
  {
    name: 'lset',
    handler: (ctx, args) => list.lset(ctx.db, args),
    arity: 4,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@slow'],
  },
  {
    name: 'linsert',
    handler: (ctx, args) => list.linsert(ctx.db, args),
    arity: 5,
    flags: ['write', 'denyoom'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@slow'],
  },
  {
    name: 'lrem',
    handler: (ctx, args) => list.lrem(ctx.db, args),
    arity: 4,
    flags: ['write'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@slow'],
  },
  {
    name: 'ltrim',
    handler: (ctx, args) => list.ltrim(ctx.db, args),
    arity: 4,
    flags: ['write'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@list', '@slow'],
  },
  {
    name: 'lpos',
    handler: (ctx, args) => list.lpos(ctx.db, args),
    arity: -3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@list', '@slow'],
  },

  // --- Set commands ---
  {
    name: 'sadd',
    handler: (ctx, args) => set.sadd(ctx.db, args),
    arity: -3,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@set', '@fast'],
  },
  {
    name: 'srem',
    handler: (ctx, args) => set.srem(ctx.db, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@set', '@fast'],
  },
  {
    name: 'sismember',
    handler: (ctx, args) => set.sismember(ctx.db, args),
    arity: 3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set', '@fast'],
  },
  {
    name: 'smismember',
    handler: (ctx, args) => set.smismember(ctx.db, args),
    arity: -3,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set', '@fast'],
  },
  {
    name: 'smembers',
    handler: (ctx, args) => set.smembers(ctx.db, args),
    arity: 2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set'],
  },
  {
    name: 'scard',
    handler: (ctx, args) => set.scard(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set', '@fast'],
  },
  {
    name: 'smove',
    handler: (ctx, args) => set.smove(ctx.db, args),
    arity: 4,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 2,
    keyStep: 1,
    categories: ['@write', '@set', '@fast'],
  },
  {
    name: 'srandmember',
    handler: (ctx, args) => set.srandmember(ctx.db, args, ctx.engine.rng),
    arity: -2,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set'],
  },
  {
    name: 'spop',
    handler: (ctx, args) => set.spop(ctx.db, args, ctx.engine.rng),
    arity: -2,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@set', '@fast'],
  },
  {
    name: 'sscan',
    handler: (ctx, args) => set.sscan(ctx.db, args),
    arity: -3,
    flags: ['readonly'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@set'],
  },

  // --- Sorted set commands ---
  {
    name: 'zadd',
    handler: (ctx, args) => sortedSet.zadd(ctx.db, args, ctx.engine.rng),
    arity: -4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@sortedset', '@fast'],
  },
  {
    name: 'zrem',
    handler: (ctx, args) => sortedSet.zrem(ctx.db, args),
    arity: -3,
    flags: ['write', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@sortedset', '@fast'],
  },
  {
    name: 'zincrby',
    handler: (ctx, args) => sortedSet.zincrby(ctx.db, args, ctx.engine.rng),
    arity: 4,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@sortedset', '@fast'],
  },
  {
    name: 'zcard',
    handler: (ctx, args) => sortedSet.zcard(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@sortedset', '@fast'],
  },

  // --- Pub/Sub commands ---
  {
    name: 'subscribe',
    handler: (ctx, args) => pubsub.subscribe(ctx, args),
    arity: -2,
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@pubsub', '@slow'],
  },
  {
    name: 'unsubscribe',
    handler: (ctx, args) => pubsub.unsubscribe(ctx, args),
    arity: -1,
    flags: ['pubsub', 'noscript', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@pubsub', '@slow'],
  },
  {
    name: 'publish',
    handler: (ctx, args) => pubsub.publish(ctx, args),
    arity: 3,
    flags: ['pubsub', 'loading', 'stale', 'fast'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@pubsub', '@fast'],
  },

  // --- Server info ---
  {
    name: 'info',
    handler: (ctx, args) => infoCmd.info(ctx, args),
    arity: -1,
    flags: ['loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@slow', '@dangerous'],
  },

  // --- Command introspection ---
  {
    name: 'command',
    handler: (ctx, args) => cmd.commandDispatch(getTable(ctx), args),
    arity: -1,
    flags: ['readonly', 'loading', 'stale'],
    firstKey: 0,
    lastKey: 0,
    keyStep: 0,
    categories: ['@slow', '@connection'],
    subcommands: [
      {
        name: 'count',
        handler: (ctx, args) => cmd.commandCount(getTable(ctx), args),
        arity: 2,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'list',
        handler: (ctx, args) => cmd.commandList(getTable(ctx), args),
        arity: -2,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'info',
        handler: (ctx, args) => cmd.commandInfo(getTable(ctx), args),
        arity: -3,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'docs',
        handler: (ctx, args) => cmd.commandDocs(getTable(ctx), args),
        arity: -2,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'getkeys',
        handler: (ctx, args) => cmd.commandGetkeys(getTable(ctx), args),
        arity: -4,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
      {
        name: 'help',
        handler: () => cmd.commandHelp(),
        arity: 2,
        flags: ['readonly', 'loading', 'stale'],
        firstKey: 0,
        lastKey: 0,
        keyStep: 0,
        categories: ['@slow', '@connection'],
      },
    ],
  },
  // --- Stream commands ---
  {
    name: 'xadd',
    handler: (ctx, args) => streamCmd.xadd(ctx.db, ctx.engine.clock(), args),
    arity: -5,
    flags: ['write', 'denyoom', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@write', '@stream', '@fast'],
  },
  {
    name: 'xlen',
    handler: (ctx, args) => streamCmd.xlen(ctx.db, args),
    arity: 2,
    flags: ['readonly', 'fast'],
    firstKey: 1,
    lastKey: 1,
    keyStep: 1,
    categories: ['@read', '@stream', '@fast'],
  },
];

/**
 * Create a new CommandTable with all implemented commands registered.
 */
export function createCommandTable(): CommandTable {
  const table = new CommandTable();
  for (const spec of commandSpecs) {
    table.register(toDefinition(spec));
  }
  return table;
}
